export const siteCopy = {
  es: {
    meta: { title: "Digital AM | Sitios Web e IA para negocios — Louisville KY" },
    ui: { languageLabel: "Idioma" },
    brand: {
      name: "Digital AM",
      tagline: "Full-Stack AI Engineer · Louisville, Kentucky · Bilingual ES/EN",
      headerCta: "Hablar con Fernando",
    },
    nav: [
      { label: "Servicios", href: "/#platform", route: false },
      { label: "Trabajos", href: "/casos", route: true },
      { label: "Sobre mí", href: "/sobre-mi", route: true },
      { label: "Precios", href: "/#pricing", route: false },
      { label: "Contacto", href: "/#contact", route: false },
    ],
    hero: {
      eyebrow: "Full-Stack AI Engineer · Louisville, Kentucky · Bilingual ES/EN",
      title: "Sitios web profesionales y sistemas de IA para negocios.",
      subtitle: "10+ apps en producción shipped. Diseño web, automatización con IA, lead capture. Construido por un Full-Stack AI Engineer en Louisville. Atención bilingüe directa.",
      primaryCta: { label: "Ver mi trabajo", href: "#work" },
      secondaryCta: { label: "Hablar conmigo", href: "#contact" },
    },
    system: {
      title: "Sistema completo: presencia + captura + automatización",
      text: "Cada componente diseñado para que un cliente que busca tu servicio en Louisville te encuentre, te contacte y se convierta — sin que vos tengas que estar disponible 24/7.",
      flow: ["Google search", "Sitio web profesional", "Lead capture", "AI automation", "CRM tracking", "Cliente confirmado"],
    },
    problem: {
      title: "Tres puntos donde la mayoría de negocios pierden clientes — y cómo los resuelvo.",
      items: [
        {
          title: "Web obsoleta o inexistente",
          text: "Una web que carga lento, no se ve en celular o no existe = cliente americano clase media-alta se va a la competencia en 8 segundos. Construyo sitios modernos en Next.js, mobile-first, con SEO local incluido.",
        },
        {
          title: "Leads que no convierten",
          text: "Visitas que llegan pero no se vuelven consulta real. Diseño formularios, CTAs y rutas WhatsApp/email pensadas para captura — con tracking real de qué funciona.",
        },
        {
          title: "Sin seguimiento automatizado",
          text: "El 78% de leads se cierran con el primero en responder. Construyo bots de WhatsApp con Claude/Gemini, secuencias de email/SMS y CRM para que cada lead se mueva sin que vos lo toques.",
        },
      ],
    },
    platform: {
      eyebrow: "Stack técnico Digital AM",
      title: "Lo que construyo: webs custom + AI agents + automation infrastructure.",
      modules: [
        {
          title: "Sitios web custom Next.js",
          text: "Built en Next.js 14 + Tailwind. Mobile-first, fast, SEO-ready. Bilingüe ES/EN si lo necesitás. Hosting en Vercel/Railway con SSL incluido.",
        },
        {
          title: "AI agents + chatbots",
          text: "Bots WhatsApp con Claude API o Gemini. Agentes conversacionales que toman pedidos, agendan citas, califican leads. Probado en producción con NotaríaPlus.",
        },
        {
          title: "Multi-tenant SaaS",
          text: "Aplicaciones SaaS con Postgres + Row-Level Security + Auth.js. Built CRMs, lead-capture systems, dashboards. Production-grade desde día uno.",
        },
        {
          title: "Automation + integrations",
          text: "Google Calendar Service Accounts, GitHub Actions CI/CD, MCP servers, Python ETL pipelines, web scraping. Conecto tu negocio con cualquier API.",
        },
      ],
    },
    work: {
      title: "Trabajos en producción — Louisville",
      linkLabel: "Ver sitio",
      items: [
        {
          title: "Empire Auto Rey",
          text: "Dealer de carros en Louisville. Pasó de solo tener WhatsApp a recibir consultas automáticas 24/7 con inventario online.",
          outcomes: ["Más consultas desde Google", "Inventario visible las 24 horas", "Citas automáticas sin llamadas"],
          href: "https://empireautorey.com/",
          status: "Activo",
        },
        {
          title: "V&M Joyería Original",
          text: "Joyería italiana en Louisville. Creamos su tienda online para que sus clientes compren desde cualquier lugar, a cualquier hora.",
          outcomes: ["Ventas online 24/7", "Clientes de todo Kentucky", "Catálogo siempre actualizado"],
          href: "https://vmluxuryjewelry.com/",
          status: "Activo",
        },
        {
          title: "Fiesta Boom Louisville",
          text: "Foto booth de lujo para eventos. Automatizamos sus reservas para que los clientes agenden solos sin llamadas ni WhatsApp.",
          outcomes: ["Reservas online sin llamadas", "Disponibilidad en tiempo real", "Más bodas y quinceañeras"],
          href: "https://fiesta-boom-louisville.vercel.app/",
          status: "Activo",
        },
      ],
    },
    pricing: {
      eyebrow: "Planes y precios",
      title: "Precios claros. Sin sorpresas. Cancelas cuando quieras.",
      text: "Elige el plan que se ajusta a tu negocio. Empezamos en 7 días desde el pago.",
      monthlyLabel: "/mes",
      annualLabel: (annual) => `o ${annual} al año`,
      featuredBadge: "Más popular",
      includesLabel: "Incluye:",
      plans: [
        {
          name: "Starter",
          tagline: "Web profesional para profesionales independientes",
          price: "$99",
          annual: "$990",
          cta: "Empezar con Starter",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Starter%20de%20%2499%2Fmes",
          features: [
            "Sitio web bilingüe ES/EN profesional",
            "Dominio .com + hosting + SSL incluidos",
            "Google Business Profile optimizado",
            "Botón WhatsApp + formulario contacto",
            "Mantenimiento + 1 update/mes",
            "Entrega en 7 días",
          ],
          featured: false,
        },
        {
          name: "Business",
          tagline: "Para tiendas, restaurantes, talleres y consultorios",
          price: "$249",
          annual: "$2,490",
          cta: "Empezar con Business",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Business%20de%20%24249%2Fmes",
          features: [
            "Todo lo del plan Starter",
            "Web multi-página (hasta 5 secciones)",
            "WhatsApp Bot con respuestas automáticas",
            "Sistema QR + automatización reseñas Google",
            "SEO local Louisville incluido",
            "Mantenimiento + 2 updates/mes",
          ],
          featured: true,
        },
        {
          name: "AI Pro",
          tagline: "Para negocios que quieren automatización + IA",
          price: "$499",
          annual: "$4,990",
          cta: "Empezar con AI Pro",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20AI%20Pro%20de%20%24499%2Fmes",
          features: [
            "Todo lo del plan Business",
            "Web custom con features a medida",
            "AI Bot WhatsApp con Claude/Gemini",
            "Email + SMS automation flows",
            "Dashboard métricas + reportes mensuales",
            "Soporte prioritario directo Fernando",
          ],
          featured: false,
        },
      ],
      guarantee: "Garantía de 30 días: si no estás contento, te devolvemos el dinero. Sin contratos largos.",
      customLabel: "¿Necesitas algo distinto?",
      customCta: "Hablemos por WhatsApp",
      customWhatsapp: "https://wa.me/18304750779?text=Hola%2C%20necesito%20un%20plan%20personalizado",
    },
    technology: {
      title: "La única agencia en Louisville que trabaja con negocios latinos, en español y en persona",
      text: "Las agencias de Miami o de otras ciudades no pueden ir a tu negocio, no entienden el mercado de Louisville y no hablan español. Nosotros sí. Esa es la diferencia que ningún competidor puede copiar.",
      items: ["Sitios web en español", "SEO local Louisville", "WhatsApp Business", "Google Business Profile", "Tiendas online", "Automatización de seguimiento", "IA incluida"],
    },
    cta: {
      title: "¿Listo para construir tu sistema digital con un AI Engineer real?",
      text: "Agenda una llamada de 30 min gratis. Revisamos tu situación actual, te muestro qué se puede hacer y te paso un plan claro. Sin compromiso, sin costo.",
      primaryCta: "Agendar llamada gratis",
      email: "ferkmas88@gmail.com",
      location: "Louisville, Kentucky · Bilingual ES/EN",
      whatsapp: "https://wa.me/18304750779",
      phone: "(830) 475-0779",
      phoneHref: "tel:+18304750779",
    },
    contact: {
      formTitle: "Cuéntanos sobre tu negocio",
      fields: {
        name: { placeholder: "Tu nombre" },
        email: { placeholder: "Tu email" },
        message: { placeholder: "¿Qué tipo de negocio tienes y qué necesitas?" },
      },
      actions: { submit: "Agenda tu auditoría gratis", submitting: "Enviando...", direct: "Escribir por WhatsApp" },
      messages: {
        incomplete: "Completa todos los campos.",
        success: "Recibido. Te contactamos en menos de 24 horas.",
        localPreview: "Abrelo desde el sitio publicado.",
        fallback: "Escríbenos directo a ferkmas88@gmail.com.",
      },
    },
    metrics: {
      title: "Trabajo real, números reales",
      text: "Lo que entrego cuando un negocio en Louisville trabaja conmigo. Sin números inflados.",
      items: [
        { value: 10, suffix: "+", label: "Apps en producción shipped" },
        { value: 24, suffix: " meses", label: "Construyendo SaaS para clientes" },
        { value: 2, suffix: "", label: "Idiomas: español + inglés profesional" },
        { value: 7, suffix: " días", label: "De idea a sitio en vivo" },
      ],
    },
    founder: {
      eyebrow: "Quién construye esto",
      title: "Soy Fernando. Full-Stack AI Engineer en Louisville.",
      text: "Cubano, Industrial Engineer + 10+ años en IT antes de pasarme full-time a software. En los últimos 24 meses he shipped 10+ aplicaciones en producción para clientes — webs profesionales, SaaS multi-tenant con Postgres + Auth, agentes de IA con Claude/Gemini, automatizaciones complejas. Hablo español nativo e inglés profesional. Trabajo directo conmigo, sin intermediarios ni becarios.",
      bullets: [
        "10+ apps en producción shipped (Next.js, Python, Postgres)",
        "Anthropic Claude API + Gemini + Ollama integrations",
        "Servicio bilingüe ES/EN — local Louisville, KY",
        "Atención directa, sin contratos largos",
      ],
      photo: "/ai-images/fernando.jpg",
      cta: { label: "Hablemos por WhatsApp", href: "https://wa.me/18304750779?text=Hola%20Fernando%2C%20quiero%20hablar%20sobre%20mi%20negocio" },
      pageTitle: "Sobre Fernando — Digital AM",
      back: "Volver al inicio",
    },
    reviews: {
      eyebrow: "Lo que dicen los dueños",
      title: "Reseñas reales de negocios en Louisville",
      text: "Sin filtros, sin reviews compradas. Si querés verlas en Google Business, hacé click en cualquiera.",
      googleCta: "Ver todas en Google",
      googleHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?sa=X&ved=1t:2428&hl=en&ictx=111",
      leaveReviewCta: "Dejá tu reseña",
      seeAllCta: "Ver todas las reseñas",
      pageTitle: "Reseñas — Digital AM",
      pageHeading: "Reseñas reales de negocios latinos en Louisville",
      pageSub: "Cada cliente acá es un negocio que conozco en persona. Si trabajaste con nosotros, dejá tu reseña abajo y se publica al revisar.",
      formTitle: "¿Trabajaste con nosotros? Dejá tu reseña",
      formNote: "Las reseñas se publican después de revisar (24h). Para que cuente más en SEO, dejala también en Google.",
      googleReviewCta: "Reseñar en Google (1 click)",
      googleWriteHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?hl=en",
      formFields: {
        name: "Tu nombre",
        business: "Negocio (ej: Mecánico Preston)",
        city: "Ciudad (ej: Louisville)",
        rating: "Estrellas",
        message: "Contá cómo te ayudamos",
        photo: "Foto opcional",
      },
      formSubmit: "Enviar reseña",
      formSubmitting: "Enviando...",
      formSuccess: "Recibida. La revisamos y se publica en 24h.",
      formError: "Algo falló. Escribime por WhatsApp.",
      back: "Volver al inicio",
      items: [
        {
          name: "Yeyo Salgado",
          business: "Yeyo Auto Sales",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotriz",
          text: "Antes la gente nos llamaba y se iba. Con la web nueva nos escriben directo por WhatsApp con el carro que quieren. Cerramos más ventas y respondemos rápido aunque estemos en el lote.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Myrna Hernández",
          business: "V&M Joyería Original",
          city: "Louisville, KY",
          rating: 5,
          industry: "retail",
          text: "Pasamos de vender solo en la tienda a tener clientes de todo Kentucky comprando online. Fernando nos armó el catálogo y nos enseñó a actualizarlo nosotros.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "La Torta Loca",
          business: "Restaurante",
          city: "Louisville, KY",
          rating: 5,
          industry: "restaurante",
          text: "El bot de WhatsApp toma pedidos cuando estamos llenos. Antes perdíamos clientes que no contestábamos. Ahora cada uno entra al sistema y ninguno se va.",
          source: "WhatsApp",
          sourceHref: "https://wa.me/18304750779",
        },
        {
          name: "Mecánico Preston",
          business: "Taller mecánico",
          city: "Louisville, KY",
          rating: 5,
          industry: "talleres",
          text: "No estaba en Google. Nadie me encontraba aunque tenía 15 años en el barrio. En 3 semanas con Fernando empezaron a entrar llamadas de clientes nuevos cada día.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Empire Auto Rey",
          business: "Dealer de carros",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotriz",
          text: "El sitio se ve serio, no como las páginas de Facebook que tienen otros dealers. Eso solo ya cambió la conversación con el cliente. Más confianza desde el primer contacto.",
          source: "Google",
          sourceHref: "https://empireautorey.com/",
        },
        {
          name: "Fiesta Boom Louisville",
          business: "Foto booth eventos",
          city: "Louisville, KY",
          rating: 5,
          industry: "eventos",
          text: "Las quinceañeras y bodas se reservan ellas solas en la web. Yo solo confirmo. Cero llamadas perdidas, cero idas y venidas por WhatsApp para cuadrar fechas.",
          source: "Google",
          sourceHref: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    casos: {
      eyebrow: "Casos en detalle",
      title: "Cómo es trabajar con Digital AM, paso a paso",
      text: "No vendemos paquetes. Diagnosticamos, ejecutamos y medimos. Estos son los casos reales de negocios en Louisville.",
      pageTitle: "Casos — Digital AM",
      pageSub: "Cada caso muestra el problema concreto, qué hicimos, y qué cambió después. Sin números inflados.",
      seeMore: "Ver caso completo",
      backHome: "Volver al inicio",
      visitSite: "Ver sitio",
      sections: { problem: "Problema", solution: "Qué hicimos", result: "Qué cambió" },
      items: [
        {
          slug: "yeyo-auto",
          title: "Yeyo Auto Sales",
          industry: "Automotriz",
          city: "Louisville, KY",
          summary: "Dealer de carros que perdía leads por no contestar a tiempo.",
          problem: "Yeyo trabajaba el lote de día. Las consultas le llegaban por WhatsApp en horarios pico, varias al mismo tiempo. Las que no contestaba en 10 minutos se iban con otro dealer. Sin web, sólo perfil de Facebook.",
          solution: "Web bilingüe con inventario embebido. Botón WhatsApp con respuesta automática inicial (datos del carro, financiamiento). Google Business optimizado con fotos del lote actualizadas semanalmente.",
          result: "Cada consulta entra al WhatsApp con el modelo que pidió + número del cliente capturado, aunque Yeyo esté manejando un trade-in. Cero leads perdidos por no contestar.",
          metric: "+ consultas calificadas",
          href: "https://empireautorey.com/",
        },
        {
          slug: "vm-joyeria",
          title: "V&M Joyería Original",
          industry: "Retail / E-commerce",
          city: "Louisville, KY",
          summary: "Joyería italiana que vendía solo en la tienda física.",
          problem: "Tienda con tráfico fuerte los fines de semana, pero clientes de Lexington, Cincinnati y otras ciudades no podían comprar entre semana. Catálogo solo en stories de Instagram que se borraban.",
          solution: "Tienda online con catálogo permanente. Sistema de pago directo, integración con Instagram Shopping, fotos profesionales del inventario.",
          result: "Ventas online recurrentes durante semana. Catálogo deja de depender de IG. Myrna actualiza precios desde el celular.",
          metric: "Clientes de todo Kentucky",
          href: "https://vmluxuryjewelry.com/",
        },
        {
          slug: "fiesta-boom",
          title: "Fiesta Boom Louisville",
          industry: "Eventos",
          city: "Louisville, KY",
          summary: "Foto booth de lujo con reservas manuales por WhatsApp.",
          problem: "Cada reserva eran 5-8 mensajes para cuadrar fecha, hora, locación, paquete. Muchas se caían en el medio. No había forma de mostrar disponibilidad real.",
          solution: "Web promocional con calendario de disponibilidad en vivo. Cliente reserva sólo, paga seña online, recibe confirmación automática.",
          result: "Reservas se cierran sin llamada. La operadora libera 8-10 horas semanales que antes se iban en chat.",
          metric: "0 llamadas para reservar",
          href: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    footer: {
      copyright: "© {year} Digital AM — Agencia de marketing digital en Louisville, KY.",
      credit: "Estrategia, diseño y desarrollo por Fernando Mastrapa.",
    },
  },

  en: {
    meta: { title: "Digital AM | Custom Websites & AI Systems · Louisville KY" },
    ui: { languageLabel: "Language" },
    brand: {
      name: "Digital AM",
      tagline: "Full-Stack AI Engineer · Louisville, Kentucky · Bilingual ES/EN",
      headerCta: "Talk to Fernando",
    },
    nav: [
      { label: "Services", href: "/#platform", route: false },
      { label: "Work", href: "/casos", route: true },
      { label: "About", href: "/sobre-mi", route: true },
      { label: "Pricing", href: "/#pricing", route: false },
      { label: "Contact", href: "/#contact", route: false },
    ],
    hero: {
      eyebrow: "Full-Stack AI Engineer · Louisville, Kentucky · Bilingual ES/EN",
      title: "Custom websites and AI systems for modern businesses.",
      subtitle: "10+ production apps shipped in the last 24 months. Built by a Full-Stack AI Engineer in Louisville. Web design, AI automation, lead capture, multi-tenant SaaS. Direct work — no intermediaries.",
      primaryCta: { label: "See my work", href: "#work" },
      secondaryCta: { label: "Talk to me", href: "#contact" },
    },
    system: {
      title: "Complete system: presence + capture + automation",
      text: "Every component designed so a customer searching your service in Louisville finds you, contacts you, and converts — without you needing to be available 24/7.",
      flow: ["Google search", "Professional website", "Lead capture", "AI automation", "CRM tracking", "Confirmed customer"],
    },
    problem: {
      title: "Three points where most businesses lose customers — and how I solve them.",
      items: [
        {
          title: "Outdated or missing website",
          text: "A site that loads slow, breaks on mobile, or doesn't exist = high-value American customer goes to competitor in 8 seconds. I build modern Next.js sites, mobile-first, with local SEO baked in.",
        },
        {
          title: "Leads that don't convert",
          text: "Visits that arrive but never become real inquiries. I design forms, CTAs and WhatsApp/email routes engineered for capture — with real tracking of what works.",
        },
        {
          title: "No follow-up automation",
          text: "78% of leads close with the first to respond. I build WhatsApp bots with Claude/Gemini, email/SMS sequences and CRM so every lead moves without you touching it.",
        },
      ],
    },
    platform: {
      eyebrow: "Digital AM tech stack",
      title: "What I build: custom websites + AI agents + automation infrastructure.",
      modules: [
        {
          title: "Custom Next.js websites",
          text: "Built in Next.js 14 + Tailwind. Mobile-first, fast, SEO-ready. Bilingual ES/EN if needed. Hosting on Vercel/Railway with SSL included.",
        },
        {
          title: "AI agents + chatbots",
          text: "WhatsApp bots powered by Claude API or Gemini. Conversational agents that take orders, schedule appointments, qualify leads. Live in production with NotaríaPlus.",
        },
        {
          title: "Multi-tenant SaaS",
          text: "SaaS apps with Postgres + Row-Level Security + Auth.js. Built CRMs, lead-capture systems, dashboards. Production-grade from day one.",
        },
        {
          title: "Automation + integrations",
          text: "Google Calendar Service Accounts, GitHub Actions CI/CD, MCP servers, Python ETL pipelines, web scraping. I connect your business to any API.",
        },
      ],
    },
    work: {
      title: "Production work — Louisville clients",
      linkLabel: "View project",
      items: [
        {
          title: "Empire Auto Rey",
          text: "Automotive website designed to present inventory clearly and make contact easier.",
          outcomes: ["Stronger brand perception", "Improved browsing experience", "Better inquiry flow"],
          href: "https://empireautorey.com/",
          status: "Live",
        },
        {
          title: "V&M Joyeria Original",
          text: "Premium ecommerce experience built to match the value of the products.",
          outcomes: ["Refined catalog presentation", "Stronger visual trust", "Better product clarity"],
          href: "https://vmluxuryjewelry.com/",
          status: "Live",
        },
        {
          title: "Fiesta Boom Louisville",
          text: "Promotional website designed to communicate services clearly and create stronger brand presence.",
          outcomes: ["Dynamic visual presence", "Clearer service communication", "Mobile-friendly experience"],
          href: "https://fiesta-boom-louisville.vercel.app/",
          status: "Live",
        },
      ],
    },
    pricing: {
      eyebrow: "Plans and pricing",
      title: "Clear pricing. No surprises. Cancel anytime.",
      text: "Pick the plan that fits your business. We start within 7 days of payment.",
      monthlyLabel: "/mo",
      annualLabel: (annual) => `or ${annual}/year`,
      featuredBadge: "Most popular",
      includesLabel: "Includes:",
      plans: [
        {
          name: "Starter",
          tagline: "For solo professionals and independents",
          price: "$99",
          annual: "$990",
          cta: "Start with Starter",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Starter%20plan%20at%20%2499%2Fmo",
          features: [
            "Professional bilingual website (ES/EN)",
            ".com domain + hosting + SSL included",
            "Google Business Profile optimized",
            "WhatsApp button + contact form",
            "Maintenance + 1 update/mo",
            "Delivery in 7 days",
          ],
          featured: false,
        },
        {
          name: "Business",
          tagline: "For shops, restaurants, mechanics and practices",
          price: "$249",
          annual: "$2,490",
          cta: "Start with Business",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Business%20plan%20at%20%24249%2Fmo",
          features: [
            "Everything in Starter",
            "Multi-page site (up to 5 sections)",
            "WhatsApp Bot with auto-replies",
            "QR + Google review automation",
            "Local Louisville SEO included",
            "Maintenance + 2 updates/mo",
          ],
          featured: true,
        },
        {
          name: "AI Pro",
          tagline: "For businesses that want automation + AI",
          price: "$499",
          annual: "$4,990",
          cta: "Start with AI Pro",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20AI%20Pro%20plan%20at%20%24499%2Fmo",
          features: [
            "Everything in Business",
            "Custom website with bespoke features",
            "AI WhatsApp Bot powered by Claude/Gemini",
            "Email + SMS automation flows",
            "Metrics dashboard + monthly reports",
            "Priority support directly with Fernando",
          ],
          featured: false,
        },
      ],
      guarantee: "30-day money-back guarantee. No long contracts.",
      customLabel: "Need something custom?",
      customCta: "Let's talk on WhatsApp",
      customWhatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%20need%20a%20custom%20plan",
    },
    technology: {
      title: "Technology behind the system",
      text: "The goal is not technology for show. It is technology used to build faster, cleaner and more reliable digital infrastructure.",
      items: ["React", "Next.js", "Node.js", "Automation workflows", "Cloud infrastructure", "Messaging systems", "AI integration"],
    },
    cta: {
      title: "Ready to build your digital system with a real AI Engineer?",
      text: "Book a free 30-min call. We review your current setup, I show you what's possible, and you walk away with a clear plan. No commitment, no cost.",
      primaryCta: "Book a free call",
      email: "ferkmas88@gmail.com",
      location: "Louisville, Kentucky · Bilingual ES/EN",
      phone: "(830) 475-0779",
      phoneHref: "tel:+18304750779",
    },
    contact: {
      formTitle: "Tell us about your business",
      fields: {
        name: { placeholder: "Name" },
        email: { placeholder: "Email" },
        message: { placeholder: "What do you need to solve?" },
      },
      actions: { submit: "Book a consultation", submitting: "Sending...", direct: "Email me directly" },
      messages: {
        incomplete: "Complete all fields before sending.",
        success: "Sent. I will reply soon.",
        localPreview: "Open from the published site.",
        fallback: "Email me directly at ferkmas88@gmail.com.",
      },
    },
    metrics: {
      title: "Real work, real numbers",
      text: "What I've actually shipped. No inflated stats.",
      items: [
        { value: 10, suffix: "+", label: "Production apps shipped" },
        { value: 24, suffix: " months", label: "Building SaaS for clients" },
        { value: 2, suffix: "", label: "Languages: Spanish + Professional English" },
        { value: 7, suffix: " days", label: "Standard delivery" },
      ],
    },
    founder: {
      eyebrow: "Who builds this",
      title: "I'm Fernando. Full-Stack AI Engineer in Louisville.",
      text: "Cuban-born, Industrial Engineer with 10+ years in IT before going full-time into software. In the last 24 months I've shipped 10+ production applications for clients — professional websites, multi-tenant SaaS with Postgres + Auth, AI agents using Claude/Gemini, complex automations. Native Spanish, professional English. You talk to me directly — no intermediaries, no juniors.",
      bullets: [
        "10+ production apps shipped (Next.js, Python, Postgres)",
        "Anthropic Claude API + Gemini + Ollama integrations",
        "Bilingual service (ES/EN) — local Louisville, KY",
        "Direct work with me. No long contracts.",
      ],
      photo: "/ai-images/fernando.jpg",
      cta: { label: "Message me on WhatsApp", href: "https://wa.me/18304750779?text=Hi%20Fernando%2C%20I%20want%20to%20talk%20about%20my%20business" },
      pageTitle: "About Fernando — Digital AM",
      back: "Back to home",
    },
    reviews: {
      eyebrow: "What owners say",
      title: "Real reviews from Louisville businesses",
      text: "No filters, no bought reviews. Click any to see the source.",
      googleCta: "View all on Google",
      googleHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?sa=X&ved=1t:2428&hl=en&ictx=111",
      leaveReviewCta: "Leave a review",
      seeAllCta: "View all reviews",
      pageTitle: "Reviews — Digital AM",
      pageHeading: "Real reviews from Latino businesses in Louisville",
      pageSub: "Every client here is a business I know personally. If you worked with us, leave a review below — published after a 24h check.",
      formTitle: "Worked with us? Leave a review",
      formNote: "Reviews go live after a 24h moderation step. For SEO weight, also drop one on Google.",
      googleReviewCta: "Review on Google (1 click)",
      googleWriteHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?hl=en",
      formFields: {
        name: "Your name",
        business: "Business (e.g. Preston Mechanic)",
        city: "City (e.g. Louisville)",
        rating: "Stars",
        message: "Tell us how we helped",
        photo: "Optional photo",
      },
      formSubmit: "Send review",
      formSubmitting: "Sending...",
      formSuccess: "Got it. We'll publish within 24h.",
      formError: "Something failed. Hit me up on WhatsApp.",
      back: "Back to home",
      items: [
        {
          name: "Yeyo Salgado",
          business: "Yeyo Auto Sales",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotive",
          text: "Before, people would call and bounce. Now they message us with the exact car they want. We close more deals and reply fast even when we're on the lot.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Myrna Hernández",
          business: "V&M Original Jewelry",
          city: "Louisville, KY",
          rating: 5,
          industry: "retail",
          text: "We went from in-store only to customers across Kentucky buying online. Fernando built the catalog and taught us to update it ourselves.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "La Torta Loca",
          business: "Restaurant",
          city: "Louisville, KY",
          rating: 5,
          industry: "restaurant",
          text: "The WhatsApp bot takes orders when we're slammed. We used to lose customers we couldn't answer. Now nobody slips through.",
          source: "WhatsApp",
          sourceHref: "https://wa.me/18304750779",
        },
        {
          name: "Preston Mechanic",
          business: "Auto repair shop",
          city: "Louisville, KY",
          rating: 5,
          industry: "auto-repair",
          text: "Wasn't even on Google. Nobody could find me even though I'd been on this block 15 years. Three weeks with Fernando and new customer calls every day.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Empire Auto Rey",
          business: "Car dealer",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotive",
          text: "The site looks serious, not like the Facebook pages other dealers run. That alone changed the first conversation with customers — more trust upfront.",
          source: "Google",
          sourceHref: "https://empireautorey.com/",
        },
        {
          name: "Fiesta Boom Louisville",
          business: "Event photo booth",
          city: "Louisville, KY",
          rating: 5,
          industry: "events",
          text: "Quinceañeras and weddings book themselves on the site. I just confirm. Zero missed calls, zero back-and-forth.",
          source: "Google",
          sourceHref: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    casos: {
      eyebrow: "Case studies",
      title: "How working with Digital AM actually goes, step by step",
      text: "We don't sell packages. We diagnose, build, and measure. These are real Louisville cases.",
      pageTitle: "Cases — Digital AM",
      pageSub: "Each case shows the actual problem, what we built, and what shifted. No inflated numbers.",
      seeMore: "See full case",
      backHome: "Back to home",
      visitSite: "Visit site",
      sections: { problem: "Problem", solution: "What we did", result: "What shifted" },
      items: [
        {
          slug: "yeyo-auto",
          title: "Yeyo Auto Sales",
          industry: "Automotive",
          city: "Louisville, KY",
          summary: "Car dealer losing leads because reply time was too slow.",
          problem: "Yeyo runs the lot during the day. Inquiries land on WhatsApp during peaks. Anything not answered in 10 minutes goes to another dealer. No website, just a Facebook page.",
          solution: "Bilingual site with inventory embed. WhatsApp button with auto-reply (car details, financing intake). Google Business optimized with weekly lot photos.",
          result: "Every inquiry hits WhatsApp with the requested model + customer number captured, even when Yeyo is mid-trade-in. Zero lost-to-silence.",
          metric: "More qualified inquiries",
          href: "https://empireautorey.com/",
        },
        {
          slug: "vm-joyeria",
          title: "V&M Original Jewelry",
          industry: "Retail / E-commerce",
          city: "Louisville, KY",
          summary: "Italian jewelry store selling only in-person.",
          problem: "Strong weekend foot traffic, but customers in Lexington and Cincinnati couldn't buy mid-week. Catalog lived in IG stories that disappeared.",
          solution: "Online store with permanent catalog. Direct payments, IG Shopping integration, professional inventory photos.",
          result: "Recurring online sales mid-week. Catalog no longer depends on IG. Myrna updates pricing from her phone.",
          metric: "Customers across Kentucky",
          href: "https://vmluxuryjewelry.com/",
        },
        {
          slug: "fiesta-boom",
          title: "Fiesta Boom Louisville",
          industry: "Events",
          city: "Louisville, KY",
          summary: "Luxury photo booth handling bookings manually over WhatsApp.",
          problem: "Each booking was 5-8 messages to nail down date, time, venue, package. Many fell through. No way to show real availability.",
          solution: "Promo site with live availability calendar. Customer books, pays deposit, receives auto-confirmation.",
          result: "Bookings close without a call. Owner reclaims 8-10 hours a week previously spent on chat.",
          metric: "0 calls to book",
          href: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    footer: {
      copyright: "© {year} Digital AM.",
      credit: "Strategy, design and development by Fernando Mastrapa.",
    },
  },
};
