export const siteCopy = {
  es: {
    meta: { title: "Páginas Web para Negocios en Louisville KY | Digital AM" },
    ui: { languageLabel: "Idioma" },
    brand: {
      name: "Digital AM",
      tagline: "Agencia local de marketing digital · Louisville, Kentucky",
      headerCta: "Ver precios",
    },
    nav: [
      { label: "Servicios", href: "#platform" },
      { label: "Trabajos", href: "#work" },
      { label: "Precios", href: "#pricing" },
      { label: "Contacto", href: "#contact" },
    ],
    hero: {
      eyebrow: "Agencia local en Louisville, Kentucky — Hablamos español",
      title: "Tu web profesional. Desde $25 al mes.",
      subtitle: "Páginas web, Google Maps y WhatsApp para negocios latinos. Lista en 7 días. Cancelas cuando quieras.",
      primaryCta: { label: "Ver planes y precios", href: "#pricing" },
      secondaryCta: { label: "Ver negocios que ayudamos", href: "#work" },
    },
    system: {
      title: "Así conseguimos más clientes para tu negocio",
      text: "Cada paso está pensado para que la gente que busca tu servicio en Louisville te encuentre, te contacte y se convierta en cliente.",
      flow: ["Google te encuentra", "Visitan tu web", "Te contactan", "Seguimiento automático", "Cliente confirmado", "Negocio crece"],
    },
    problem: {
      title: "Cada día que no apareces en Google, alguien en Louisville llama a tu competencia.",
      items: [
        {
          title: "Tu negocio no aparece en Google",
          text: "Facebook e Instagram son terreno prestado. Si no tienes web propia optimizada, los clientes que buscan tu servicio en Louisville nunca te encuentran.",
        },
        {
          title: "Los clientes no saben cómo contactarte",
          text: "Llegan a tu perfil, no encuentran cómo contactarte fácil, y se van con quien sí tiene web. Cada visita perdida es dinero que no entra.",
        },
        {
          title: "Sin respuesta rápida, pierdes la venta",
          text: "El 78% de los clientes contratan al primero que les responde. Sin automatización, tus clientes se van con la competencia mientras tú estás ocupado trabajando.",
        },
      ],
    },
    platform: {
      eyebrow: "Cómo conseguimos clientes para tu negocio",
      title: "Un sistema completo para que te encuentren, te contacten y te elijan a ti.",
      modules: [
        {
          title: "Aparecer en Google cuando te buscan",
          text: "Diseñamos tu sitio web en español e inglés optimizado para SEO local. Cuando alguien busca tu servicio en Louisville, tu negocio aparece primero.",
        },
        {
          title: "Convertir visitas en llamadas reales",
          text: "Formularios y botones de WhatsApp estratégicamente ubicados para que cada persona que visita tu web se convierta en una consulta real.",
        },
        {
          title: "Nunca perder un cliente por no responder",
          text: "Tu negocio responde automáticamente al instante — por SMS, WhatsApp o email — aunque estés ocupado trabajando.",
        },
        {
          title: "Saber exactamente qué cliente sigue",
          text: "Organizamos todos tus leads en un solo panel para que nunca pierdas una venta y siempre sepas cuál es el siguiente paso.",
        },
      ],
    },
    work: {
      title: "Negocios de Louisville que ya trabajan con nosotros",
      linkLabel: "Ver sitio",
      items: [
        {
          title: "Empire Auto Rey",
          text: "Dealer de carros en Louisville. Pasó de solo tener WhatsApp a recibir consultas automáticas 24/7 con inventario online.",
          outcomes: ["Más consultas desde Google", "Inventario visible las 24 horas", "Citas automáticas sin llamadas"],
          href: "https://empireautorey.com/",
          status: "Activo",
        },
        {
          title: "V&M Joyería Original",
          text: "Joyería italiana en Louisville. Creamos su tienda online para que sus clientes compren desde cualquier lugar, a cualquier hora.",
          outcomes: ["Ventas online 24/7", "Clientes de todo Kentucky", "Catálogo siempre actualizado"],
          href: "https://vmluxuryjewelry.com/",
          status: "Activo",
        },
        {
          title: "Fiesta Boom Louisville",
          text: "Foto booth de lujo para eventos. Automatizamos sus reservas para que los clientes agenden solos sin llamadas ni WhatsApp.",
          outcomes: ["Reservas online sin llamadas", "Disponibilidad en tiempo real", "Más bodas y quinceañeras"],
          href: "https://fiesta-boom-louisville.vercel.app/",
          status: "Activo",
        },
      ],
    },
    pricing: {
      eyebrow: "Planes y precios",
      title: "Precios claros. Sin sorpresas. Cancelas cuando quieras.",
      text: "Elige el plan que se ajusta a tu negocio. Empezamos en 7 días desde el pago.",
      monthlyLabel: "/mes",
      annualLabel: (annual) => `o ${annual} al año`,
      featuredBadge: "Más popular",
      includesLabel: "Incluye:",
      plans: [
        {
          name: "Solo",
          tagline: "Para emprendedores y freelancers",
          price: "$25",
          annual: "$250",
          cta: "Empezar con Solo",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Solo%20de%20%2425%2Fmes",
          features: [
            "Página web 1 sección bilingüe ES/EN",
            "Dominio .com + hosting incluidos",
            "Botón WhatsApp + formulario de contacto",
            "Google Business Profile optimizado",
            "1 actualización al mes",
            "Entrega en 7 días",
          ],
          featured: false,
        },
        {
          name: "Negocio",
          tagline: "Para tiendas, salones, talleres y restaurantes",
          price: "$45",
          annual: "$450",
          cta: "Empezar con Negocio",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Negocio%20de%20%2445%2Fmes",
          features: [
            "Todo lo del plan Solo",
            "Página web hasta 3 secciones",
            "WhatsApp Bot con respuestas automáticas",
            "Sistema QR para reseñas en Google",
            "2 actualizaciones al mes",
            "Entrega en 10 días",
          ],
          featured: true,
        },
        {
          name: "Pro",
          tagline: "Para negocios con equipo y varios servicios",
          price: "$75",
          annual: "$750",
          cta: "Empezar con Pro",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Pro%20de%20%2475%2Fmes",
          features: [
            "Todo lo del plan Negocio",
            "Página web hasta 5 secciones",
            "WhatsApp Bot con IA + seguimiento por email y SMS",
            "4 actualizaciones al mes",
            "Reportes mensuales de visitas y leads",
            "Soporte prioritario",
          ],
          featured: false,
        },
      ],
      guarantee: "Garantía de 30 días: si no estás contento, te devolvemos el dinero. Sin contratos largos.",
      customLabel: "¿Necesitas algo distinto?",
      customCta: "Hablemos por WhatsApp",
      customWhatsapp: "https://wa.me/18304750779?text=Hola%2C%20necesito%20un%20plan%20personalizado",
    },
    technology: {
      title: "La única agencia en Louisville que trabaja con negocios latinos, en español y en persona",
      text: "Las agencias de Miami o de otras ciudades no pueden ir a tu negocio, no entienden el mercado de Louisville y no hablan español. Nosotros sí. Esa es la diferencia que ningún competidor puede copiar.",
      items: ["Sitios web en español", "SEO local Louisville", "WhatsApp Business", "Google Business Profile", "Tiendas online", "Automatización de seguimiento", "IA incluida"],
    },
    cta: {
      title: "¿Listo para que tu negocio consiga más clientes en Louisville?",
      text: "Agenda tu auditoría digital gratis. En 30 minutos te decimos exactamente por qué no estás apareciendo en Google y qué necesitas para cambiar eso. Sin compromiso, sin costo.",
      primaryCta: "Agenda tu auditoría gratis",
      email: "ferkmas88@gmail.com",
      location: "Louisville, Kentucky",
      whatsapp: "https://wa.me/18304750779",
    },
    contact: {
      formTitle: "Cuéntanos sobre tu negocio",
      fields: {
        name: { placeholder: "Tu nombre" },
        email: { placeholder: "Tu email" },
        message: { placeholder: "¿Qué tipo de negocio tienes y qué necesitas?" },
      },
      actions: { submit: "Agenda tu auditoría gratis", submitting: "Enviando...", direct: "Escribir por WhatsApp" },
      messages: {
        incomplete: "Completa todos los campos.",
        success: "Recibido. Te contactamos en menos de 24 horas.",
        localPreview: "Abrelo desde el sitio publicado.",
        fallback: "Escríbenos directo a ferkmas88@gmail.com.",
      },
    },
    footer: {
      copyright: "© {year} Digital AM — Agencia de marketing digital en Louisville, KY.",
      credit: "Estrategia, diseño y desarrollo por Fernando Martinez.",
    },
  },

  en: {
    meta: { title: "Digital AM | Digital systems for modern businesses" },
    ui: { languageLabel: "Language" },
    brand: {
      name: "Digital AM",
      tagline: "Digital systems studio · Louisville, Kentucky",
      headerCta: "See pricing",
    },
    nav: [
      { label: "Platform", href: "#platform" },
      { label: "Work", href: "#work" },
      { label: "Pricing", href: "#pricing" },
      { label: "Contact", href: "#contact" },
    ],
    hero: {
      eyebrow: "Digital systems studio · Louisville, Kentucky",
      title: "Your professional website. From $25 a month.",
      subtitle: "Websites, Google Maps and WhatsApp for local businesses. Live in 7 days. Cancel anytime.",
      primaryCta: { label: "See plans and pricing", href: "#pricing" },
      secondaryCta: { label: "View work", href: "#work" },
    },
    system: {
      title: "One connected growth system",
      text: "From first visit to follow-up, every step of the customer journey should move forward without friction.",
      flow: ["Traffic", "Website", "Lead Capture", "Automation", "CRM", "Customer"],
    },
    problem: {
      title: "Most businesses lose opportunities before the conversation even starts",
      items: [
        {
          title: "Outdated presence",
          text: "Weak digital presence reduces trust before the conversation even begins.",
        },
        {
          title: "Lost leads",
          text: "Visitors show interest but slow or unclear contact routes make opportunities disappear.",
        },
        {
          title: "Slow follow-up",
          text: "Without automation or structure, warm inquiries go cold before receiving attention.",
        },
      ],
    },
    platform: {
      eyebrow: "Digital AM Platform",
      title: "Digital infrastructure designed to attract, capture and convert.",
      modules: [
        {
          title: "Website System",
          text: "Premium websites built to communicate value clearly and build trust immediately.",
        },
        {
          title: "Lead Capture",
          text: "Smart forms and messaging routes that convert visits into real inquiries.",
        },
        {
          title: "Automation",
          text: "SMS and workflow automation that responds instantly and keeps leads moving.",
        },
        {
          title: "CRM Structure",
          text: "Organized pipelines that ensure every opportunity is tracked and moves forward.",
        },
      ],
    },
    work: {
      title: "Selected work",
      linkLabel: "View project",
      items: [
        {
          title: "Empire Auto Rey",
          text: "Automotive website designed to present inventory clearly and make contact easier.",
          outcomes: ["Stronger brand perception", "Improved browsing experience", "Better inquiry flow"],
          href: "https://empireautorey.com/",
          status: "Live",
        },
        {
          title: "V&M Joyeria Original",
          text: "Premium ecommerce experience built to match the value of the products.",
          outcomes: ["Refined catalog presentation", "Stronger visual trust", "Better product clarity"],
          href: "https://vmluxuryjewelry.com/",
          status: "Live",
        },
        {
          title: "Fiesta Boom Louisville",
          text: "Promotional website designed to communicate services clearly and create stronger brand presence.",
          outcomes: ["Dynamic visual presence", "Clearer service communication", "Mobile-friendly experience"],
          href: "https://fiesta-boom-louisville.vercel.app/",
          status: "Live",
        },
      ],
    },
    pricing: {
      eyebrow: "Plans and pricing",
      title: "Clear pricing. No surprises. Cancel anytime.",
      text: "Pick the plan that fits your business. We start within 7 days of payment.",
      monthlyLabel: "/mo",
      annualLabel: (annual) => `or ${annual}/year`,
      featuredBadge: "Most popular",
      includesLabel: "Includes:",
      plans: [
        {
          name: "Solo",
          tagline: "For solo operators and freelancers",
          price: "$25",
          annual: "$250",
          cta: "Start with Solo",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Solo%20plan%20at%20%2425%2Fmo",
          features: [
            "1-section bilingual website (ES/EN)",
            ".com domain + hosting included",
            "WhatsApp button + contact form",
            "Google Business Profile setup",
            "1 update per month",
            "Delivery in 7 days",
          ],
          featured: false,
        },
        {
          name: "Business",
          tagline: "For shops, salons, mechanics and restaurants",
          price: "$45",
          annual: "$450",
          cta: "Start with Business",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Business%20plan%20at%20%2445%2Fmo",
          features: [
            "Everything in Solo",
            "Up to 3-section website",
            "WhatsApp Bot with auto-replies",
            "QR review system for Google",
            "2 updates per month",
            "Delivery in 10 days",
          ],
          featured: true,
        },
        {
          name: "Pro",
          tagline: "For teams and multi-service businesses",
          price: "$75",
          annual: "$750",
          cta: "Start with Pro",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Pro%20plan%20at%20%2475%2Fmo",
          features: [
            "Everything in Business",
            "Up to 5-section website",
            "AI WhatsApp Bot + email/SMS follow-up",
            "4 updates per month",
            "Monthly traffic and lead reports",
            "Priority support",
          ],
          featured: false,
        },
      ],
      guarantee: "30-day money-back guarantee. No long contracts.",
      customLabel: "Need something custom?",
      customCta: "Let's talk on WhatsApp",
      customWhatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%20need%20a%20custom%20plan",
    },
    technology: {
      title: "Technology behind the system",
      text: "The goal is not technology for show. It is technology used to build faster, cleaner and more reliable digital infrastructure.",
      items: ["React", "Next.js", "Node.js", "Automation workflows", "Cloud infrastructure", "Messaging systems", "AI integration"],
    },
    cta: {
      title: "Build the digital base your business needs",
      text: "Whether you need a stronger website, better lead capture or smarter follow-up systems, Digital AM helps you build it with clarity.",
      primaryCta: "Book a consultation",
      email: "ferkmas88@gmail.com",
      location: "Louisville, Kentucky",
    },
    contact: {
      formTitle: "Tell us about your business",
      fields: {
        name: { placeholder: "Name" },
        email: { placeholder: "Email" },
        message: { placeholder: "What do you need to solve?" },
      },
      actions: { submit: "Book a consultation", submitting: "Sending...", direct: "Email me directly" },
      messages: {
        incomplete: "Complete all fields before sending.",
        success: "Sent. I will reply soon.",
        localPreview: "Open from the published site.",
        fallback: "Email me directly at ferkmas88@gmail.com.",
      },
    },
    footer: {
      copyright: "© {year} Digital AM.",
      credit: "Strategy, design and development by Fernando Martinez.",
    },
  },
};
