export const siteCopy = {
  es: {
    meta: { title: "Páginas Web para Negocios en Louisville KY | Digital AM" },
    ui: { languageLabel: "Idioma" },
    brand: {
      name: "Digital AM",
      tagline: "Agencia local de marketing digital · Louisville, Kentucky",
      headerCta: "Ver precios",
    },
    nav: [
      { label: "Servicios", href: "/#platform", route: false },
      { label: "Trabajos", href: "/casos", route: true },
      { label: "Reseñas", href: "/resenas", route: true },
      { label: "Sobre mí", href: "/sobre-mi", route: true },
      { label: "Precios", href: "/#pricing", route: false },
      { label: "Contacto", href: "/#contact", route: false },
    ],
    hero: {
      eyebrow: "Agencia local en Louisville, Kentucky — Hablamos español",
      title: "Tu web profesional. Desde $25 al mes.",
      subtitle: "Páginas web, Google Maps y WhatsApp para negocios latinos. Lista en 7 días. Cancelas cuando quieras.",
      primaryCta: { label: "Ver planes y precios", href: "#pricing" },
      secondaryCta: { label: "Ver negocios que ayudamos", href: "#work" },
    },
    system: {
      title: "Así conseguimos más clientes para tu negocio",
      text: "Cada paso está pensado para que la gente que busca tu servicio en Louisville te encuentre, te contacte y se convierta en cliente.",
      flow: ["Google te encuentra", "Visitan tu web", "Te contactan", "Seguimiento automático", "Cliente confirmado", "Negocio crece"],
    },
    problem: {
      title: "Cada día que no apareces en Google, alguien en Louisville llama a tu competencia.",
      items: [
        {
          title: "Tu negocio no aparece en Google",
          text: "Facebook e Instagram son terreno prestado. Si no tienes web propia optimizada, los clientes que buscan tu servicio en Louisville nunca te encuentran.",
        },
        {
          title: "Los clientes no saben cómo contactarte",
          text: "Llegan a tu perfil, no encuentran cómo contactarte fácil, y se van con quien sí tiene web. Cada visita perdida es dinero que no entra.",
        },
        {
          title: "Sin respuesta rápida, pierdes la venta",
          text: "El 78% de los clientes contratan al primero que les responde. Sin automatización, tus clientes se van con la competencia mientras tú estás ocupado trabajando.",
        },
      ],
    },
    platform: {
      eyebrow: "Cómo conseguimos clientes para tu negocio",
      title: "Un sistema completo para que te encuentren, te contacten y te elijan a ti.",
      modules: [
        {
          title: "Aparecer en Google cuando te buscan",
          text: "Diseñamos tu sitio web en español e inglés optimizado para SEO local. Cuando alguien busca tu servicio en Louisville, tu negocio aparece primero.",
        },
        {
          title: "Convertir visitas en llamadas reales",
          text: "Formularios y botones de WhatsApp estratégicamente ubicados para que cada persona que visita tu web se convierta en una consulta real.",
        },
        {
          title: "Nunca perder un cliente por no responder",
          text: "Tu negocio responde automáticamente al instante — por SMS, WhatsApp o email — aunque estés ocupado trabajando.",
        },
        {
          title: "Saber exactamente qué cliente sigue",
          text: "Organizamos todos tus leads en un solo panel para que nunca pierdas una venta y siempre sepas cuál es el siguiente paso.",
        },
      ],
    },
    work: {
      title: "Negocios de Louisville que ya trabajan con nosotros",
      linkLabel: "Ver sitio",
      items: [
        {
          title: "Empire Auto Rey",
          text: "Dealer de carros en Louisville. Pasó de solo tener WhatsApp a recibir consultas automáticas 24/7 con inventario online.",
          outcomes: ["Más consultas desde Google", "Inventario visible las 24 horas", "Citas automáticas sin llamadas"],
          href: "https://empireautorey.com/",
          status: "Activo",
        },
        {
          title: "V&M Joyería Original",
          text: "Joyería italiana en Louisville. Creamos su tienda online para que sus clientes compren desde cualquier lugar, a cualquier hora.",
          outcomes: ["Ventas online 24/7", "Clientes de todo Kentucky", "Catálogo siempre actualizado"],
          href: "https://vmluxuryjewelry.com/",
          status: "Activo",
        },
        {
          title: "Fiesta Boom Louisville",
          text: "Foto booth de lujo para eventos. Automatizamos sus reservas para que los clientes agenden solos sin llamadas ni WhatsApp.",
          outcomes: ["Reservas online sin llamadas", "Disponibilidad en tiempo real", "Más bodas y quinceañeras"],
          href: "https://fiesta-boom-louisville.vercel.app/",
          status: "Activo",
        },
      ],
    },
    pricing: {
      eyebrow: "Planes y precios",
      title: "Precios claros. Sin sorpresas. Cancelas cuando quieras.",
      text: "Elige el plan que se ajusta a tu negocio. Empezamos en 7 días desde el pago.",
      monthlyLabel: "/mes",
      annualLabel: (annual) => `o ${annual} al año`,
      featuredBadge: "Más popular",
      includesLabel: "Incluye:",
      plans: [
        {
          name: "Solo",
          tagline: "Para emprendedores y freelancers",
          price: "$25",
          annual: "$250",
          cta: "Empezar con Solo",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Solo%20de%20%2425%2Fmes",
          features: [
            "Página web 1 sección bilingüe ES/EN",
            "Dominio .com + hosting incluidos",
            "Botón WhatsApp + formulario de contacto",
            "Google Business Profile optimizado",
            "1 actualización al mes",
            "Entrega en 7 días",
          ],
          featured: false,
        },
        {
          name: "Negocio",
          tagline: "Para tiendas, salones, talleres y restaurantes",
          price: "$45",
          annual: "$450",
          cta: "Empezar con Negocio",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Negocio%20de%20%2445%2Fmes",
          features: [
            "Todo lo del plan Solo",
            "Página web hasta 3 secciones",
            "WhatsApp Bot con respuestas automáticas",
            "Sistema QR para reseñas en Google",
            "2 actualizaciones al mes",
            "Entrega en 10 días",
          ],
          featured: true,
        },
        {
          name: "Pro",
          tagline: "Para negocios con equipo y varios servicios",
          price: "$75",
          annual: "$750",
          cta: "Empezar con Pro",
          whatsapp: "https://wa.me/18304750779?text=Hola%2C%20me%20interesa%20el%20plan%20Pro%20de%20%2475%2Fmes",
          features: [
            "Todo lo del plan Negocio",
            "Página web hasta 5 secciones",
            "WhatsApp Bot con IA + seguimiento por email y SMS",
            "4 actualizaciones al mes",
            "Reportes mensuales de visitas y leads",
            "Soporte prioritario",
          ],
          featured: false,
        },
      ],
      guarantee: "Garantía de 30 días: si no estás contento, te devolvemos el dinero. Sin contratos largos.",
      customLabel: "¿Necesitas algo distinto?",
      customCta: "Hablemos por WhatsApp",
      customWhatsapp: "https://wa.me/18304750779?text=Hola%2C%20necesito%20un%20plan%20personalizado",
    },
    technology: {
      title: "La única agencia en Louisville que trabaja con negocios latinos, en español y en persona",
      text: "Las agencias de Miami o de otras ciudades no pueden ir a tu negocio, no entienden el mercado de Louisville y no hablan español. Nosotros sí. Esa es la diferencia que ningún competidor puede copiar.",
      items: ["Sitios web en español", "SEO local Louisville", "WhatsApp Business", "Google Business Profile", "Tiendas online", "Automatización de seguimiento", "IA incluida"],
    },
    cta: {
      title: "¿Listo para que tu negocio consiga más clientes en Louisville?",
      text: "Agenda tu auditoría digital gratis. En 30 minutos te decimos exactamente por qué no estás apareciendo en Google y qué necesitas para cambiar eso. Sin compromiso, sin costo.",
      primaryCta: "Agenda tu auditoría gratis",
      email: "ferkmas88@gmail.com",
      location: "Louisville, Kentucky",
      whatsapp: "https://wa.me/18304750779",
    },
    contact: {
      formTitle: "Cuéntanos sobre tu negocio",
      fields: {
        name: { placeholder: "Tu nombre" },
        email: { placeholder: "Tu email" },
        message: { placeholder: "¿Qué tipo de negocio tienes y qué necesitas?" },
      },
      actions: { submit: "Agenda tu auditoría gratis", submitting: "Enviando...", direct: "Escribir por WhatsApp" },
      messages: {
        incomplete: "Completa todos los campos.",
        success: "Recibido. Te contactamos en menos de 24 horas.",
        localPreview: "Abrelo desde el sitio publicado.",
        fallback: "Escríbenos directo a ferkmas88@gmail.com.",
      },
    },
    metrics: {
      title: "Resultados, no promesas",
      text: "Lo que pasa cuando un negocio en Louisville activa su sistema digital con nosotros.",
      items: [
        { value: 12, suffix: "+", label: "Negocios activos" },
        { value: 92, suffix: "%", label: "Clientes que renuevan" },
        { value: 7, suffix: " días", label: "De idea a sitio en vivo" },
        { value: 24, suffix: "/7", label: "Respuesta automática" },
      ],
    },
    founder: {
      eyebrow: "Quién está detrás",
      title: "Soy Fernando. Vivo en Louisville. Y trabajo solo con negocios latinos.",
      text: "Cubano, llegué a Kentucky buscando lo mismo que tú: que el negocio crezca sin que dependa de tu suerte. De día trabajo en Home Depot, de noche y fines de semana construyo Digital AM. Por eso no contesto en 3 días — contesto cuando me escribes. Hablo español, voy en persona a tu local, y entiendo cómo se mueve el cliente latino en USA porque soy uno.",
      bullets: [
        "Atención directa conmigo, no con un becario.",
        "Hablamos en español, sin traducciones forzadas.",
        "Voy a tu negocio en Louisville si hace falta.",
        "Sin contratos largos. Si no funciona, te vas.",
      ],
      photo: "/ai-images/fernando.jpg",
      cta: { label: "Hablemos por WhatsApp", href: "https://wa.me/18304750779?text=Hola%20Fernando%2C%20quiero%20hablar%20sobre%20mi%20negocio" },
      pageTitle: "Sobre Fernando — Digital AM",
      back: "Volver al inicio",
    },
    reviews: {
      eyebrow: "Lo que dicen los dueños",
      title: "Reseñas reales de negocios en Louisville",
      text: "Sin filtros, sin reviews compradas. Si querés verlas en Google Business, hacé click en cualquiera.",
      googleCta: "Ver todas en Google",
      googleHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?sa=X&ved=1t:2428&hl=en&ictx=111",
      leaveReviewCta: "Dejá tu reseña",
      seeAllCta: "Ver todas las reseñas",
      pageTitle: "Reseñas — Digital AM",
      pageHeading: "Reseñas reales de negocios latinos en Louisville",
      pageSub: "Cada cliente acá es un negocio que conozco en persona. Si trabajaste con nosotros, dejá tu reseña abajo y se publica al revisar.",
      formTitle: "¿Trabajaste con nosotros? Dejá tu reseña",
      formNote: "Las reseñas se publican después de revisar (24h). Para que cuente más en SEO, dejala también en Google.",
      googleReviewCta: "Reseñar en Google (1 click)",
      googleWriteHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?hl=en",
      formFields: {
        name: "Tu nombre",
        business: "Negocio (ej: Mecánico Preston)",
        city: "Ciudad (ej: Louisville)",
        rating: "Estrellas",
        message: "Contá cómo te ayudamos",
        photo: "Foto opcional",
      },
      formSubmit: "Enviar reseña",
      formSubmitting: "Enviando...",
      formSuccess: "Recibida. La revisamos y se publica en 24h.",
      formError: "Algo falló. Escribime por WhatsApp.",
      back: "Volver al inicio",
      items: [
        {
          name: "Yeyo Salgado",
          business: "Yeyo Auto Sales",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotriz",
          text: "Antes la gente nos llamaba y se iba. Con la web nueva nos escriben directo por WhatsApp con el carro que quieren. Cerramos más ventas y respondemos rápido aunque estemos en el lote.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Myrna Hernández",
          business: "V&M Joyería Original",
          city: "Louisville, KY",
          rating: 5,
          industry: "retail",
          text: "Pasamos de vender solo en la tienda a tener clientes de todo Kentucky comprando online. Fernando nos armó el catálogo y nos enseñó a actualizarlo nosotros.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "La Torta Loca",
          business: "Restaurante",
          city: "Louisville, KY",
          rating: 5,
          industry: "restaurante",
          text: "El bot de WhatsApp toma pedidos cuando estamos llenos. Antes perdíamos clientes que no contestábamos. Ahora cada uno entra al sistema y ninguno se va.",
          source: "WhatsApp",
          sourceHref: "https://wa.me/18304750779",
        },
        {
          name: "Mecánico Preston",
          business: "Taller mecánico",
          city: "Louisville, KY",
          rating: 5,
          industry: "talleres",
          text: "No estaba en Google. Nadie me encontraba aunque tenía 15 años en el barrio. En 3 semanas con Fernando empezaron a entrar llamadas de clientes nuevos cada día.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Empire Auto Rey",
          business: "Dealer de carros",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotriz",
          text: "El sitio se ve serio, no como las páginas de Facebook que tienen otros dealers. Eso solo ya cambió la conversación con el cliente. Más confianza desde el primer contacto.",
          source: "Google",
          sourceHref: "https://empireautorey.com/",
        },
        {
          name: "Fiesta Boom Louisville",
          business: "Foto booth eventos",
          city: "Louisville, KY",
          rating: 5,
          industry: "eventos",
          text: "Las quinceañeras y bodas se reservan ellas solas en la web. Yo solo confirmo. Cero llamadas perdidas, cero idas y venidas por WhatsApp para cuadrar fechas.",
          source: "Google",
          sourceHref: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    casos: {
      eyebrow: "Casos en detalle",
      title: "Cómo es trabajar con Digital AM, paso a paso",
      text: "No vendemos paquetes. Diagnosticamos, ejecutamos y medimos. Estos son los casos reales de negocios en Louisville.",
      pageTitle: "Casos — Digital AM",
      pageSub: "Cada caso muestra el problema concreto, qué hicimos, y qué cambió después. Sin números inflados.",
      seeMore: "Ver caso completo",
      backHome: "Volver al inicio",
      visitSite: "Ver sitio",
      sections: { problem: "Problema", solution: "Qué hicimos", result: "Qué cambió" },
      items: [
        {
          slug: "yeyo-auto",
          title: "Yeyo Auto Sales",
          industry: "Automotriz",
          city: "Louisville, KY",
          summary: "Dealer de carros que perdía leads por no contestar a tiempo.",
          problem: "Yeyo trabajaba el lote de día. Las consultas le llegaban por WhatsApp en horarios pico, varias al mismo tiempo. Las que no contestaba en 10 minutos se iban con otro dealer. Sin web, sólo perfil de Facebook.",
          solution: "Web bilingüe con inventario embebido. Botón WhatsApp con respuesta automática inicial (datos del carro, financiamiento). Google Business optimizado con fotos del lote actualizadas semanalmente.",
          result: "Cada consulta entra al WhatsApp con el modelo que pidió + número del cliente capturado, aunque Yeyo esté manejando un trade-in. Cero leads perdidos por no contestar.",
          metric: "+ consultas calificadas",
          href: "https://empireautorey.com/",
        },
        {
          slug: "vm-joyeria",
          title: "V&M Joyería Original",
          industry: "Retail / E-commerce",
          city: "Louisville, KY",
          summary: "Joyería italiana que vendía solo en la tienda física.",
          problem: "Tienda con tráfico fuerte los fines de semana, pero clientes de Lexington, Cincinnati y otras ciudades no podían comprar entre semana. Catálogo solo en stories de Instagram que se borraban.",
          solution: "Tienda online con catálogo permanente. Sistema de pago directo, integración con Instagram Shopping, fotos profesionales del inventario.",
          result: "Ventas online recurrentes durante semana. Catálogo deja de depender de IG. Myrna actualiza precios desde el celular.",
          metric: "Clientes de todo Kentucky",
          href: "https://vmluxuryjewelry.com/",
        },
        {
          slug: "fiesta-boom",
          title: "Fiesta Boom Louisville",
          industry: "Eventos",
          city: "Louisville, KY",
          summary: "Foto booth de lujo con reservas manuales por WhatsApp.",
          problem: "Cada reserva eran 5-8 mensajes para cuadrar fecha, hora, locación, paquete. Muchas se caían en el medio. No había forma de mostrar disponibilidad real.",
          solution: "Web promocional con calendario de disponibilidad en vivo. Cliente reserva sólo, paga seña online, recibe confirmación automática.",
          result: "Reservas se cierran sin llamada. La operadora libera 8-10 horas semanales que antes se iban en chat.",
          metric: "0 llamadas para reservar",
          href: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    footer: {
      copyright: "© {year} Digital AM — Agencia de marketing digital en Louisville, KY.",
      credit: "Estrategia, diseño y desarrollo por Fernando Mastrapa.",
    },
  },

  en: {
    meta: { title: "Digital AM | Digital systems for modern businesses" },
    ui: { languageLabel: "Language" },
    brand: {
      name: "Digital AM",
      tagline: "Digital systems studio · Louisville, Kentucky",
      headerCta: "See pricing",
    },
    nav: [
      { label: "Services", href: "/#platform", route: false },
      { label: "Work", href: "/casos", route: true },
      { label: "Reviews", href: "/resenas", route: true },
      { label: "About", href: "/sobre-mi", route: true },
      { label: "Pricing", href: "/#pricing", route: false },
      { label: "Contact", href: "/#contact", route: false },
    ],
    hero: {
      eyebrow: "Digital systems studio · Louisville, Kentucky",
      title: "Your professional website. From $25 a month.",
      subtitle: "Websites, Google Maps and WhatsApp for local businesses. Live in 7 days. Cancel anytime.",
      primaryCta: { label: "See plans and pricing", href: "#pricing" },
      secondaryCta: { label: "View work", href: "#work" },
    },
    system: {
      title: "One connected growth system",
      text: "From first visit to follow-up, every step of the customer journey should move forward without friction.",
      flow: ["Traffic", "Website", "Lead Capture", "Automation", "CRM", "Customer"],
    },
    problem: {
      title: "Most businesses lose opportunities before the conversation even starts",
      items: [
        {
          title: "Outdated presence",
          text: "Weak digital presence reduces trust before the conversation even begins.",
        },
        {
          title: "Lost leads",
          text: "Visitors show interest but slow or unclear contact routes make opportunities disappear.",
        },
        {
          title: "Slow follow-up",
          text: "Without automation or structure, warm inquiries go cold before receiving attention.",
        },
      ],
    },
    platform: {
      eyebrow: "Digital AM Platform",
      title: "Digital infrastructure designed to attract, capture and convert.",
      modules: [
        {
          title: "Website System",
          text: "Premium websites built to communicate value clearly and build trust immediately.",
        },
        {
          title: "Lead Capture",
          text: "Smart forms and messaging routes that convert visits into real inquiries.",
        },
        {
          title: "Automation",
          text: "SMS and workflow automation that responds instantly and keeps leads moving.",
        },
        {
          title: "CRM Structure",
          text: "Organized pipelines that ensure every opportunity is tracked and moves forward.",
        },
      ],
    },
    work: {
      title: "Selected work",
      linkLabel: "View project",
      items: [
        {
          title: "Empire Auto Rey",
          text: "Automotive website designed to present inventory clearly and make contact easier.",
          outcomes: ["Stronger brand perception", "Improved browsing experience", "Better inquiry flow"],
          href: "https://empireautorey.com/",
          status: "Live",
        },
        {
          title: "V&M Joyeria Original",
          text: "Premium ecommerce experience built to match the value of the products.",
          outcomes: ["Refined catalog presentation", "Stronger visual trust", "Better product clarity"],
          href: "https://vmluxuryjewelry.com/",
          status: "Live",
        },
        {
          title: "Fiesta Boom Louisville",
          text: "Promotional website designed to communicate services clearly and create stronger brand presence.",
          outcomes: ["Dynamic visual presence", "Clearer service communication", "Mobile-friendly experience"],
          href: "https://fiesta-boom-louisville.vercel.app/",
          status: "Live",
        },
      ],
    },
    pricing: {
      eyebrow: "Plans and pricing",
      title: "Clear pricing. No surprises. Cancel anytime.",
      text: "Pick the plan that fits your business. We start within 7 days of payment.",
      monthlyLabel: "/mo",
      annualLabel: (annual) => `or ${annual}/year`,
      featuredBadge: "Most popular",
      includesLabel: "Includes:",
      plans: [
        {
          name: "Solo",
          tagline: "For solo operators and freelancers",
          price: "$25",
          annual: "$250",
          cta: "Start with Solo",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Solo%20plan%20at%20%2425%2Fmo",
          features: [
            "1-section bilingual website (ES/EN)",
            ".com domain + hosting included",
            "WhatsApp button + contact form",
            "Google Business Profile setup",
            "1 update per month",
            "Delivery in 7 days",
          ],
          featured: false,
        },
        {
          name: "Business",
          tagline: "For shops, salons, mechanics and restaurants",
          price: "$45",
          annual: "$450",
          cta: "Start with Business",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Business%20plan%20at%20%2445%2Fmo",
          features: [
            "Everything in Solo",
            "Up to 3-section website",
            "WhatsApp Bot with auto-replies",
            "QR review system for Google",
            "2 updates per month",
            "Delivery in 10 days",
          ],
          featured: true,
        },
        {
          name: "Pro",
          tagline: "For teams and multi-service businesses",
          price: "$75",
          annual: "$750",
          cta: "Start with Pro",
          whatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%27m%20interested%20in%20the%20Pro%20plan%20at%20%2475%2Fmo",
          features: [
            "Everything in Business",
            "Up to 5-section website",
            "AI WhatsApp Bot + email/SMS follow-up",
            "4 updates per month",
            "Monthly traffic and lead reports",
            "Priority support",
          ],
          featured: false,
        },
      ],
      guarantee: "30-day money-back guarantee. No long contracts.",
      customLabel: "Need something custom?",
      customCta: "Let's talk on WhatsApp",
      customWhatsapp: "https://wa.me/18304750779?text=Hi%2C%20I%20need%20a%20custom%20plan",
    },
    technology: {
      title: "Technology behind the system",
      text: "The goal is not technology for show. It is technology used to build faster, cleaner and more reliable digital infrastructure.",
      items: ["React", "Next.js", "Node.js", "Automation workflows", "Cloud infrastructure", "Messaging systems", "AI integration"],
    },
    cta: {
      title: "Build the digital base your business needs",
      text: "Whether you need a stronger website, better lead capture or smarter follow-up systems, Digital AM helps you build it with clarity.",
      primaryCta: "Book a consultation",
      email: "ferkmas88@gmail.com",
      location: "Louisville, Kentucky",
    },
    contact: {
      formTitle: "Tell us about your business",
      fields: {
        name: { placeholder: "Name" },
        email: { placeholder: "Email" },
        message: { placeholder: "What do you need to solve?" },
      },
      actions: { submit: "Book a consultation", submitting: "Sending...", direct: "Email me directly" },
      messages: {
        incomplete: "Complete all fields before sending.",
        success: "Sent. I will reply soon.",
        localPreview: "Open from the published site.",
        fallback: "Email me directly at ferkmas88@gmail.com.",
      },
    },
    metrics: {
      title: "Outcomes, not promises",
      text: "What happens when a Louisville business activates a real digital system.",
      items: [
        { value: 12, suffix: "+", label: "Active clients" },
        { value: 92, suffix: "%", label: "Renewal rate" },
        { value: 7, suffix: " days", label: "Idea to live site" },
        { value: 24, suffix: "/7", label: "Auto response" },
      ],
    },
    founder: {
      eyebrow: "Who builds this",
      title: "I'm Fernando. I live in Louisville. I work only with Latino-owned businesses.",
      text: "Cuban, came to Kentucky for the same reason you're here: to grow without depending on luck. By day I work at Home Depot, by night and weekends I build Digital AM. That's why you talk to me, not an intern. I speak Spanish, I show up in person, and I know how the Latino customer in the US actually moves — because I'm one.",
      bullets: [
        "You talk to me directly, not a junior.",
        "Spanish first, English when you need it.",
        "I show up at your shop in Louisville.",
        "No long contracts. Cancel anytime.",
      ],
      photo: "/ai-images/fernando.jpg",
      cta: { label: "Message me on WhatsApp", href: "https://wa.me/18304750779?text=Hi%20Fernando%2C%20I%20want%20to%20talk%20about%20my%20business" },
      pageTitle: "About Fernando — Digital AM",
      back: "Back to home",
    },
    reviews: {
      eyebrow: "What owners say",
      title: "Real reviews from Louisville businesses",
      text: "No filters, no bought reviews. Click any to see the source.",
      googleCta: "View all on Google",
      googleHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?sa=X&ved=1t:2428&hl=en&ictx=111",
      leaveReviewCta: "Leave a review",
      seeAllCta: "View all reviews",
      pageTitle: "Reviews — Digital AM",
      pageHeading: "Real reviews from Latino businesses in Louisville",
      pageSub: "Every client here is a business I know personally. If you worked with us, leave a review below — published after a 24h check.",
      formTitle: "Worked with us? Leave a review",
      formNote: "Reviews go live after a 24h moderation step. For SEO weight, also drop one on Google.",
      googleReviewCta: "Review on Google (1 click)",
      googleWriteHref: "https://www.google.com/maps/place/Digital+AM/data=!4m2!3m1!1s0x0:0x5a39e2fc9edbd6d8?hl=en",
      formFields: {
        name: "Your name",
        business: "Business (e.g. Preston Mechanic)",
        city: "City (e.g. Louisville)",
        rating: "Stars",
        message: "Tell us how we helped",
        photo: "Optional photo",
      },
      formSubmit: "Send review",
      formSubmitting: "Sending...",
      formSuccess: "Got it. We'll publish within 24h.",
      formError: "Something failed. Hit me up on WhatsApp.",
      back: "Back to home",
      items: [
        {
          name: "Yeyo Salgado",
          business: "Yeyo Auto Sales",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotive",
          text: "Before, people would call and bounce. Now they message us with the exact car they want. We close more deals and reply fast even when we're on the lot.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Myrna Hernández",
          business: "V&M Original Jewelry",
          city: "Louisville, KY",
          rating: 5,
          industry: "retail",
          text: "We went from in-store only to customers across Kentucky buying online. Fernando built the catalog and taught us to update it ourselves.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "La Torta Loca",
          business: "Restaurant",
          city: "Louisville, KY",
          rating: 5,
          industry: "restaurant",
          text: "The WhatsApp bot takes orders when we're slammed. We used to lose customers we couldn't answer. Now nobody slips through.",
          source: "WhatsApp",
          sourceHref: "https://wa.me/18304750779",
        },
        {
          name: "Preston Mechanic",
          business: "Auto repair shop",
          city: "Louisville, KY",
          rating: 5,
          industry: "auto-repair",
          text: "Wasn't even on Google. Nobody could find me even though I'd been on this block 15 years. Three weeks with Fernando and new customer calls every day.",
          source: "Google",
          sourceHref: "https://www.google.com/maps",
        },
        {
          name: "Empire Auto Rey",
          business: "Car dealer",
          city: "Louisville, KY",
          rating: 5,
          industry: "automotive",
          text: "The site looks serious, not like the Facebook pages other dealers run. That alone changed the first conversation with customers — more trust upfront.",
          source: "Google",
          sourceHref: "https://empireautorey.com/",
        },
        {
          name: "Fiesta Boom Louisville",
          business: "Event photo booth",
          city: "Louisville, KY",
          rating: 5,
          industry: "events",
          text: "Quinceañeras and weddings book themselves on the site. I just confirm. Zero missed calls, zero back-and-forth.",
          source: "Google",
          sourceHref: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    casos: {
      eyebrow: "Case studies",
      title: "How working with Digital AM actually goes, step by step",
      text: "We don't sell packages. We diagnose, build, and measure. These are real Louisville cases.",
      pageTitle: "Cases — Digital AM",
      pageSub: "Each case shows the actual problem, what we built, and what shifted. No inflated numbers.",
      seeMore: "See full case",
      backHome: "Back to home",
      visitSite: "Visit site",
      sections: { problem: "Problem", solution: "What we did", result: "What shifted" },
      items: [
        {
          slug: "yeyo-auto",
          title: "Yeyo Auto Sales",
          industry: "Automotive",
          city: "Louisville, KY",
          summary: "Car dealer losing leads because reply time was too slow.",
          problem: "Yeyo runs the lot during the day. Inquiries land on WhatsApp during peaks. Anything not answered in 10 minutes goes to another dealer. No website, just a Facebook page.",
          solution: "Bilingual site with inventory embed. WhatsApp button with auto-reply (car details, financing intake). Google Business optimized with weekly lot photos.",
          result: "Every inquiry hits WhatsApp with the requested model + customer number captured, even when Yeyo is mid-trade-in. Zero lost-to-silence.",
          metric: "More qualified inquiries",
          href: "https://empireautorey.com/",
        },
        {
          slug: "vm-joyeria",
          title: "V&M Original Jewelry",
          industry: "Retail / E-commerce",
          city: "Louisville, KY",
          summary: "Italian jewelry store selling only in-person.",
          problem: "Strong weekend foot traffic, but customers in Lexington and Cincinnati couldn't buy mid-week. Catalog lived in IG stories that disappeared.",
          solution: "Online store with permanent catalog. Direct payments, IG Shopping integration, professional inventory photos.",
          result: "Recurring online sales mid-week. Catalog no longer depends on IG. Myrna updates pricing from her phone.",
          metric: "Customers across Kentucky",
          href: "https://vmluxuryjewelry.com/",
        },
        {
          slug: "fiesta-boom",
          title: "Fiesta Boom Louisville",
          industry: "Events",
          city: "Louisville, KY",
          summary: "Luxury photo booth handling bookings manually over WhatsApp.",
          problem: "Each booking was 5-8 messages to nail down date, time, venue, package. Many fell through. No way to show real availability.",
          solution: "Promo site with live availability calendar. Customer books, pays deposit, receives auto-confirmation.",
          result: "Bookings close without a call. Owner reclaims 8-10 hours a week previously spent on chat.",
          metric: "0 calls to book",
          href: "https://fiesta-boom-louisville.vercel.app/",
        },
      ],
    },
    footer: {
      copyright: "© {year} Digital AM.",
      credit: "Strategy, design and development by Fernando Mastrapa.",
    },
  },
};
